name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'ext/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'ext/**'
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build build --config Debug
